set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(UTEST_FOLDER "utests")
set (ARTIFACTS_FOLDER "artifacts")
set (OUT_DOXYGEN_FOLDER "${ARTIFACTS_FOLDER}/doxygen"
)
set (DOCS_FOLDER "${CMAKE_SOURCE_DIR}/docs"
)